from app.models.teacher import Teacher
from app.models.parent import Parent
from app.models.class_ import Class
from app.models.subject import Subject
from app.models.class_subject import ClassSubject
from app.models.student import Student
from app.models.assessment import Assessment
from app.models.assessment_score import AssessmentScore
from app.models.weekly_record import WeeklyRecord
from app.models.weekly_observation import WeeklyObservation
from app.models.ai_report import AIReport
from app.models.activity import Activity
from app.models.message import ChatMessage
from app.models.parent_question import ParentQuestion
from app.models.question_reply import QuestionReply
from app.models.canvas_sync_log import CanvasSyncLog
from app.models.parent_feedback import ParentFeedback
from app.models.translation_cache import TranslationCache
